const api=(path,body)=>fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body&&JSON.stringify(body)}).then(r=>r.json());
let page='apps', query='';
const nav=[['apps','앱'],['automations','자동화'],['workspace','워크스페이스'],['settings','설정']];
function esc(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function layout(body){document.querySelector('#app').innerHTML=`<main class="shell"><aside class="side"><div class="brand">OPUS</div>${nav.map(([id,name])=>`<button class="nav ${page===id?'active':''}" data-nav="${id}">${name}</button>`).join('')}</aside><section class="content">${body}</section></main>`;document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{page=x.dataset.nav;render()})}
function toast(message){const n=document.createElement('div');n.className='notice';n.textContent=message;document.body.append(n);setTimeout(()=>n.remove(),2600)}
async function apps(){const data=await api('apps');const list=data.apps.filter(a=>a.name.toLowerCase().includes(query.toLowerCase()));layout(`<div class="top"><div><h1 class="title">앱</h1><p class="sub">승인된 카탈로그에서 필요한 도구를 설치하고 관리하세요.</p></div><input class="search" placeholder="앱 검색" value="${esc(query)}"></div><div class="grid">${list.map(a=>{const installed=data.installed.includes(a.id);return `<article class="card"><div class="row"><span class="icon">${a.icon}</span><span class="tag">${a.category}</span></div><h3>${a.name}</h3><p>${a.description}</p><p class="muted">v${a.version} · ${a.permissions.join(', ')}</p><button class="${installed?'danger':'primary'}" data-app="${a.id}" data-installed="${installed}">${installed?'제거':'설치'}</button></article>`}).join('')}</div>`);document.querySelector('.search').oninput=e=>{query=e.target.value;apps()};document.querySelectorAll('[data-app]').forEach(b=>b.onclick=async()=>{const action=b.dataset.installed==='true'?'uninstall':'install';const r=await api(`apps/${b.dataset.app}/${action}`,{});toast(r.message);apps()})}
async function automations(){const flows=await api('automations');layout(`<div class="top"><div><h1 class="title">자동화</h1><p class="sub">순서대로 조합해 내 PC와 설치한 앱을 움직입니다.</p></div><button class="primary" id="new-flow">새 자동화</button></div><div class="list">${flows.map(f=>`<article class="item flow"><div class="row"><div><h3>${esc(f.name)}</h3><span class="muted">${f.enabled?'활성화됨':'꺼짐'} · ${f.actions.length}개 동작</span></div><span class="tag">단축어</span></div>${f.actions.map(a=>`<div class="step ${['if','repeat','end'].includes(a.type)?'control':''}"><span>${a.type==='if'?'조건문':a.type==='repeat'?'반복':a.type==='end'?'끝':esc(a.label)}</span><span class="muted">${a.type}</span></div>`).join('')}</article>`).join('')}</div>`);document.querySelector('#new-flow').onclick=async()=>{await api('automations',{name:'새 자동화',enabled:true,actions:[{type:'set_setting',label:'Windows 설정 변경'},{type:'if',label:'조건이 참이면'},{type:'repeat',label:'반복 실행'},{type:'end',label:'블록 종료'}]});automations()}}
async function workspace(){const w=await api('workspace');layout(`<h1 class="title">${esc(w.name)}</h1><p class="sub">내 역할: ${w.role==='admin'?'관리자':'부관리자'} · 장치와 배포를 한 곳에서 관리합니다.</p><div class="item"><div class="device muted"><span>장치</span><span>상태</span><span>역할</span><span></span></div>${w.devices.map(d=>`<div class="device" style="padding:13px 0;border-top:1px solid var(--line)"><strong>${esc(d.name)}</strong><span class="${d.status}">${d.status==='online'?'온라인':'오프라인'}</span><span>${d.role==='managed'?'관리 대상':d.role==='operator'?'부관리자':'관리자'}</span><button class="secondary" data-device="${d.id}">작업 보내기</button></div>`).join('')}</div><p class="muted">원격 제어는 이 MVP에서 작업 대기열까지만 기록합니다. 실제 배포 전에는 장치 인증과 명령 서명이 필요합니다.</p>`);document.querySelectorAll('[data-device]').forEach(b=>b.onclick=async()=>{await api('workspace/command',{targets:[b.dataset.device],action:'sync'});toast('장치 작업이 대기열에 추가되었습니다.')})}
async function settings(){const sources=await api('sources');layout(`<h1 class="title">설정</h1><p class="sub">카탈로그 원본과 보안 정책을 관리합니다.</p><div class="list">${sources.map(s=>`<article class="item"><div class="row"><div><h3>${esc(s.name)}</h3><p class="muted">${esc(s.repository)} · ${esc(s.branch)}/${esc(s.catalogPath)}</p></div><button class="secondary" data-sync="${esc(s.id)}">지금 동기화</button></div></article>`).join('')}</div><p class="muted">동기화는 Git으로 원본을 읽기 전용으로 복제합니다. 설치 명령은 여기서 실행되지 않습니다.</p>`);document.querySelectorAll('[data-sync]').forEach(b=>b.onclick=async()=>{b.disabled=true;const r=await api('sources/sync',{id:b.dataset.sync});toast(r.error||`${r.name} 동기화 완료`);b.disabled=false})}
function render(){({apps,automations,workspace,settings})[page]()};render();
